version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: camunda_postgres
    environment:
      POSTGRES_USER: camunda
      POSTGRES_PASSWORD: password
      POSTGRES_DB: camunda
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
