spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda
    username: camunda
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    filter:
      create: All tasks
    generic-properties:
      properties:
        historyTimeToLive: P1D
    database:
      type: postgres
      schema-update: true
    history-level: full
